---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---

Here, we're just setting a few options.

```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

```{r prepare_codebook}
library(tidyverse)
library(codebook)
library(haven)
library(labelled)

rr_human_data_with_reversed_items = rio::import("../synth-rep-dataset/data/processed/sosci_labelled.rds")
reversed_items <- str_sub(names(rr_human_data_with_reversed_items)[str_detect(names(rr_human_data_with_reversed_items), "_R$")], 1, -3)
rr_human_data_with_inclusion_criteria = rio::import("../synth-rep-dataset/data/processed/sosci_labelled_with_exclusion_criteria.rds")
# setdiff(names(rr_human_data_with_inclusion_criteria), names(rr_human_data_with_reversed_items)) %>% dput()
rr_human_data_with_inclusion_criteria <- rr_human_data_with_inclusion_criteria %>% select(one_of(c("CASE","even_odd", "psychant", 
"psychsyn", "mahal_dist", 
"longstring", "time_per_item", "not_serious", "included")))
rr_human_data_with_inclusion_criteria <- rr_human_data_with_inclusion_criteria %>% 
  full_join(rr_human_data_with_reversed_items)
rr_human_data_included <- rr_human_data_with_inclusion_criteria %>% filter(included) %>% 
  select(-starts_with("BH"), -starts_with("WS"), -starts_with("BFI"),
         -QUESTNNR, -MODE, -one_of(reversed_items), -IFI_01, -ACH_01, -ACH_02, 
         -IFI_02, -FRI_02, -starts_with("MS"), -matches("^OC[0-9]"), -starts_with("PR"),
         -starts_with("RG"), -starts_with("ZY"))

rr_human_data_included <- rr_human_data_included %>% mutate(
  Age = as.numeric(Age)) %>% 
  rename(sex = gender,
         gender = SD13,
         Age_prolific = Age,
         age = SD02_01,
         race = SD03,
         hispanic = SD04,
         education = SD08,
         occupation = SD10) %>% 
  mutate(
    non_hispanic_white = if_else(race == "White" & hispanic == "No, not of Hispanic, Latino, or Spanish origin", 1, 0)
  ) %>% 
  select(sex, gender, age, race, hispanic, education, occupation, starts_with("SD"), everything())

table(rr_human_data_included$sex)
round(prop.table(table(rr_human_data_included$sex)),2)
table(rr_human_data_included$gender)

options(digits = 2)
table(rr_human_data_included$occupation == "N/A: Unemployed")
prop.table(table(rr_human_data_included$occupation == "N/A: Unemployed"))
rr_human_data_included %>% summarise(
  nh_white = sum(non_hispanic_white),
  nh_white_pc = sum(non_hispanic_white)/n(),
  hispanic = sum(hispanic != "No, not of Hispanic, Latino, or Spanish origin"),
  hispanic_pc = sum(hispanic)/n(),
  black = sum(race == "Black/African American"),
  black_pc = sum(black)/n(),
)

table(rr_human_data_included$education)
round(prop.table(table(rr_human_data_included$education))*100)
table(rr_human_data_included$SD07)

table(rr_human_data_included$Nationality != "United States")

rr_human_data_included %>% group_by(education) %>% 
  summarise(n())
# table(str_replace_all(str_to_lower(str_trim(rr_human_data_included$SD13_02)), "-", ""))
```

```{r}
rr_human_data_share <- rr_human_data_included %>% select(
  CASE, 
  # Demographic variables
  age, Age_prolific, sex, gender,
  education, occupation, Nationality,
  race, hispanic, non_hispanic_white,
  
  # Metadata/Quality Control variables
  even_odd, psychant, psychsyn, mahal_dist,
  longstring, time_per_item, included, not_serious,
  Language, total_approvals = `Total approvals`,
  
  # Main questionnaire items (using starts_with)
  starts_with(c("AAID", "PANAS", "PAQ", "PSS", "NEPS", 
                "ULS", "FCV", "DAQ", "CESD", "HEXACO", 
                "OCIR", "PTQ", "RAAS", "KSA", "SAS", 
                "MFQ", "CQ", "OLBI", "UWES", "WGS")),
  
  # Explicitly exclude reversed items
  -ends_with("_R"),
  
  # Explicitly exclude other prefixes/patterns
  -starts_with(c("BH", "WS", "BFI", "MS", "PR", "RG", "ZY")),
  -matches("^OC[0-9]"),
)

haven::write_sav(rr_human_data_share, "docs/rr_data.sav")
rio::export(rr_human_data_share, "docs/rr_data.csv")
rio::export(rr_human_data_share, "docs/rr_data.rds")
```


```{r codebook}
codebook(rr_human_data_included)
```
